In [588]:
import sys
sys.path.append("C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\Working_attributes")
from Imports import *

Defs:

In [ ]:
# def for checking str in every file
def find_str_in_all_files(str_to_find):
    in_dict = {}
    for count in range(len(files_df)):
        str_to_find_lower = str_to_find.strip().lower()
        file = files_df.loc[count,'files']
        data = pd.read_excel(f'{files_df.loc[count,"folder"]}\\{file}', sheet_name=sheet_name)
        try:
            str_index = data[data.apply(lambda row: row.astype(str).str.lower().str.contains(str_to_find_lower).any(), axis=1)].index.item()
            in_dict[file] = str_index
        except:
            continue
    return files_df.shape[0], len(in_dict.keys()), in_dict

# def for finfing str index
def find_id_str(str_to_find):
    str_to_find_lower = str_to_find.strip().lower()
    id_str = new_data[new_data.apply(lambda row: row.astype(str).str.lower().str.contains(str_to_find_lower).any(), axis=1)].index.item()
    return id_str

def diff_by_cols(data_col_names, data_merge, count_start_col=1, data_for_cols=True):
    
    if data_for_cols==False:
        cols_list = ['Value']
    else:
        # cols lisr without name col (first)
        cols_list = data_col_names.columns.tolist()[count_start_col:]

    for col in cols_list:
        # choose only cols with previous col in name
        col_cols_list = [x for x,y in zip(data_merge.columns,data_merge.columns.str.contains(col)) if y==True]
        assert len(col_cols_list) == 2
        # print diff
        data_merge[f'{col}_diff'] = -1*(data_merge[col_cols_list[0]] - data_merge[col_cols_list[1]])
        # print pct diff
        data_merge[f'{col}_pct_diff'] = 0 
        # condition = abs(data_merge[[col_cols_list[0],col_cols_list[1]]]).max(axis=1)!=0
        # data_merge.loc[condition, f'{col}_pct_diff'] = data_merge.loc[condition,f'{col}_diff'] / abs(data_merge.loc[condition,[col_cols_list[0],col_cols_list[1]]]).max(axis=1)
        condition = data_merge[col_cols_list[0]]!=0
        data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
        data_merge[f'{col}_pct_diff'] = np.sign(data_merge[f'{col}_diff']) * data_merge[f'{col}_pct_diff']

    return data_merge

def del_null_data(data):
    list_to_del = [np.nan, '0', 0]
    # del empty rows
    data = data[(~data.isin(list_to_del)).any(axis=1)]
    # del empty cols
    cols_list = (~data.isin(list_to_del)).any(axis=0)
    cols_list = cols_list[cols_list==True].index.tolist()
    data = data[cols_list]
    return data

def data_to_parts(data,need_to_name=False):
    string_to_find = 'TOTAL'
    string_to_find = string_to_find.strip().lower()
    try:
        assert data.iloc[0,5].strip().lower() == string_to_find
        part_col = 6
    except:
        part_col = 5
    asserts_part = data.iloc[:,:part_col]
    asserts_part.columns = ['name'] + asserts_part.iloc[0,:].tolist()[1:]
    if need_to_name == True:
        asserts_part['class_name_1'] = 'Assets'
        asserts_part = asserts_part.iloc[2:,:]
    else:
        asserts_part = asserts_part.iloc[1:,:]

    liabilities_part = data.iloc[:,part_col:part_col+part_col]
    liabilities_part.columns = ['name'] + liabilities_part.iloc[0,:].tolist()[1:]
    if need_to_name == True:
        liabilities_part['class_name_1'] = 'Liabilities and equity'
        liabilities_part = liabilities_part.iloc[2:,:]
    else:
        liabilities_part = liabilities_part.iloc[1:,:]

    data = pd.concat([asserts_part,liabilities_part],axis=0).reset_index(drop=True)
    return data

Variables

In [ ]:
print_to_excel = True

sheet_name = 'FX Exposure_Balance Sheet'
month = ['nov','dec']
month = month[0]

In [ ]:
folders = [x for x in os.listdir() if month in x]
files_list = []
folders_for_df = []
for count in range(len(folders)):
    files_folder_list = os.listdir(f'{folders[count]}')
    files_folder_list = [x for x in files_folder_list if '~' not in x]
    files_list += files_folder_list
    folders_for_df += [folders[count] for x in range(len(files_folder_list))]
files_list

['BRFTO FX Exposure Model 28.11.2024 - With Pnl & Tax Credit -New Model.xlsx',
 'BRSFT FX Exposure Model 28.11.2024 - With Pnl & Tax Credit.xlsx',
 'Cópia de BRFHRG FX Exposure 28.11.2024 - With pnl  Tax Credit - New model.xlsx',
 'BRFHRG FX Exposure 29.11.2024 - With pnl  Tax Credit - New model.xlsx',
 'BRFTO FX Exposure Model 29.11.2024 - With Pnl & Tax Credit -New Model.xlsx',
 'BRSFT FX Exposure Model 29.11.2024 - With Pnl & Tax Credit.xlsx']

In [ ]:
files_df = pd.DataFrame({'files':files_list, 'folder':folders_for_df})
files_df['day'] = files_df.files.str.extract(r'([0-9]{2}.[0-9]{2}.[0-9]{4})')
files_df['company'] = files_df.files.str.extract(r'(BR\w* )')
files_df

,files,folder,day,company
0,BRFTO FX Exposure Model 28.11.2024 - With Pnl ...,28 nov,28.11.2024,BRFTO
1,BRSFT FX Exposure Model 28.11.2024 - With Pnl ...,28 nov,28.11.2024,BRSFT
2,Cópia de BRFHRG FX Exposure 28.11.2024 - With ...,28 nov,28.11.2024,BRFHRG
3,BRFHRG FX Exposure 29.11.2024 - With pnl Tax ...,29 nov,29.11.2024,BRFHRG
4,BRFTO FX Exposure Model 29.11.2024 - With Pnl ...,29 nov,29.11.2024,BRFTO
5,BRSFT FX Exposure Model 29.11.2024 - With Pnl ...,29 nov,29.11.2024,BRSFT

In [ ]:
files_df_merge = files_df.merge(files_df, on='company', suffixes=['_old','_new'])
files_df_couple = files_df_merge[(files_df_merge.day_old!=files_df_merge.day_new)&(files_df_merge.day_old<files_df_merge.day_new)]
files_df_couple = files_df_couple.reset_index(drop=True)
files_df_couple

,files_old,folder_old,day_old,company,files_new,folder_new,day_new
0,BRFTO FX Exposure Model 28.11.2024 - With Pnl ...,28 nov,28.11.2024,BRFTO,BRFTO FX Exposure Model 29.11.2024 - With Pnl ...,29 nov,29.11.2024
1,BRSFT FX Exposure Model 28.11.2024 - With Pnl ...,28 nov,28.11.2024,BRSFT,BRSFT FX Exposure Model 29.11.2024 - With Pnl ...,29 nov,29.11.2024
2,Cópia de BRFHRG FX Exposure 28.11.2024 - With ...,28 nov,28.11.2024,BRFHRG,BRFHRG FX Exposure 29.11.2024 - With pnl Tax ...,29 nov,29.11.2024

Counting

In [600]:
if print_to_excel == True:
    Output_file = f'{str(date.today())}_Brazil_monitoring.xlsx'
    with pd.ExcelWriter(Output_file, engine='openpyxl', mode='w') as writer:
        files_df_couple.to_excel(writer, index=False, sheet_name='all_files')

for string_id in files_df_couple.index:
    # try:
    # read old data
    old_path = f'{files_df_couple.loc[string_id, "folder_old"]}\\{files_df_couple.loc[string_id, "files_old"]}'
    old_data = pd.read_excel(old_path, sheet_name=sheet_name)
    old_data_date = files_df_couple.loc[string_id, "day_old"]
    print(old_path)

    # read new data
    new_path = f'{files_df_couple.loc[string_id, "folder_new"]}\\{files_df_couple.loc[string_id, "files_new"]}'
    new_data = pd.read_excel(new_path, sheet_name=sheet_name)
    new_data_date = files_df_couple.loc[string_id, "day_new"]
    print(new_path)

    company_name = files_df_couple.loc[string_id, "company"]

    count_data_date = 0
    for data_date in [old_data, new_data]:
        
        count_data_date += 1



        ### DATA_1
        # 1)	сначала видеть изменение общей позиции, суммарной день ко 
        # 2)	затем видеть изменение on-Balance и Off-Balance
        start_str = 'USD Equivalent'
        end_str = 'Net Exposure Balance BRL'

        data_1 = data_date.loc[find_id_str(start_str):find_id_str(end_str),]
        data_1 = del_null_data(data_1)
        data_1 = data_1.iloc[:,:3].reset_index(drop=True)
        data_1.columns = ['name'] + data_1.iloc[0,1:].values.tolist()

        ### DATA_3
        # 3)	затем видеть изменение итоговых балансовых статей:
        start_str = 'USD denominated'
        end_str = 'Total assets'
        data_3 = data_date.loc[[find_id_str(start_str),find_id_str(end_str)],]
        data_3 = del_null_data(data_3)

        data_3 = data_to_parts(data_3)

        col_1_name_data_3 = 'Total balance and off-balance items'

        data_3_tr = data_3.transpose()
        # rename cols and drop col name string
        data_3_tr.columns = data_3_tr.iloc[0,:]
        data_3_tr = data_3_tr.iloc[1:,:]
        data_3_tr['name'] = data_3_tr.index
        data_3_tr = data_3_tr.reset_index(drop=True)
        # to parts
        assets_col = [x for x in data_3_tr.columns.tolist() if 'assets' in x][0]
        liabilities_col = [x for x in data_3_tr.columns.tolist() if 'liabilities' in x][0]


        assets_data = data_3_tr[['name',assets_col]]
        assets_data.columns = [col_1_name_data_3, 'Value']
        assets_data['Balance item class'] = 'Assets'
        liabilities_data = data_3_tr[['name',liabilities_col]]
        liabilities_data.columns = [col_1_name_data_3, 'Value']
        liabilities_data['Balance item class'] = 'Liabilities and equity'

        data_3_tr = pd.concat([assets_data,liabilities_data], axis=0)
        data_3_tr = data_3_tr.iloc[:,[2,0,1]]

        data_3 = data_3_tr

        ### DATA_4
        # 4)	затем видеть изменения внебалансовых статей (их немного)
        start_str = 'Total assets'
        end_str = 'Total Off Balance Assets'
        pre_data_4 = data_date.loc[find_id_str(start_str):find_id_str(end_str),]

        start_str = 'Assets'
        header_str = 'USD denominated'
        start_id = pre_data_4.loc[pre_data_4['Unnamed: 1']=='Assets',:].index.item()
        data_4 = pre_data_4.loc[start_id:]

        header_df = data_date.loc[find_id_str(header_str):find_id_str(header_str)+1,]
        data_4 = pd.concat([header_df,data_4],axis=0)
        data_4 = del_null_data(data_4)

        data_4 = data_to_parts(data_4, True)

        data_4 = data_4[~data_4.iloc[:,0].isna()].reset_index(drop=True)
        # del empty cols
        cols_list = (~data_4.isin(list_to_del)).any(axis=0)
        cols_list = cols_list[cols_list==True].index.tolist()
        data_4 = data_4[cols_list]

        data_4 = data_4[['class_name_1'] + data_4.columns.tolist()[:-1]]

        # del string
        str_to_find = 'Industrialization'
        str_to_find = str_to_find.strip().lower()
        data_4 = data_4[~data_4.name.str.lower().str.contains(str_to_find)]

        # total to previous part
        str_to_find = 'total'

        data_to_3 = data_4[data_4.name.str.lower().str.contains(str_to_find)]
        data_to_3 = data_to_3.iloc[:,:3]
        data_to_3.columns = ['Balance item class', col_1_name_data_3, 'Value']
        data_to_3.iloc[:,1] = 'Off balance'

        data_3 = pd.concat([data_3,data_to_3],axis=0)

        #final 4 part
        data_4 = data_4[~data_4.name.str.lower().str.contains(str_to_find)]
        data_4 = data_4.iloc[:, :3]
        data_4.columns = ['Balance item class','Off- balance items','Value']

        ### DATA_5
        # 5)	затем видеть детальное изменение балансовых статей.
        start_str = 'USD denominated'
        end_str = 'Total assets'
        data_5 = data_date.loc[find_id_str(start_str):find_id_str(end_str)-1,]
        data_5 = del_null_data(data_5)

        data_5 = data_to_parts(data_5, True)

        data_5 = data_5[~data_5.iloc[:,0].isna()].reset_index(drop=True)

        class_name_list = ['Current assets','Non-current assets','Current liabilities','Non-current liabilities','Equity']
        class_name_list_lower = list(map(lambda x: x.strip().lower(), class_name_list))
        data_5['class_name_2'] = np.nan
        condition = data_5.name.str.strip().str.lower().isin(class_name_list_lower)
        data_5.loc[condition, 'class_name_2'] = data_5.loc[condition, 'name']
        data_5['class_name_2'] = data_5['class_name_2'].fillna(method='ffill')
        data_5 = data_5[(data_5.name!=data_5.class_name_2)|(data_5.name=='Equity')].reset_index(drop=True)

        data_5 = data_5[['class_name_1', 'class_name_2'] + data_5.columns.tolist()[:-2]]

        data_5_melt = data_5.melt(id_vars=data_5.columns.tolist()[:3], value_vars=data_5.columns.tolist()[3:], value_name='Value', var_name='Exposure currency type')
        data_5_melt = data_5_melt.iloc[:,1:]
        data_5_melt.columns = ['Balance item class','Balance item name'] + data_5_melt.columns.tolist()[2:]
        data_5 = data_5_melt
        

        if count_data_date == 1:
            data_1_old = data_1
            data_3_old = data_3
            data_4_old = data_4
            data_5_old = data_5
        if count_data_date == 2:
            data_1_new = data_1
            data_3_new = data_3
            data_4_new = data_4
            data_5_new = data_5

    # concat old and new data
    ### data_1
    data_1_merge = data_1_old.merge(data_1_new, how='outer', on='name', suffixes=[f'_{old_data_date}',f'_{new_data_date}'])
    data_1_merge = data_1_merge[~data_1_merge.name.isna()]
    data_1_merge = diff_by_cols(data_1_new,data_1_merge)

    col_1_name_net = 'Total net exposure'
    col_1_name_data_1 = 'Total exposure split by Balance/Off balance'

    str_to_find = 'Net Exposure Balance BRL'
    str_to_find = str_to_find.strip().lower()
    data_total = data_1_merge[data_1_merge.name.str.lower().str.contains(str_to_find)]
    data_total.columns = [col_1_name_net] + data_total.columns.tolist()[1:]

    data_total_data_1 = data_1_merge[~data_1_merge.name.str.lower().str.contains(str_to_find)]
    data_total_data_1.columns = [col_1_name_data_1] + data_total_data_1.columns.tolist()[1:]

    ### data_3
    data_3_merge = data_3_old.merge(data_3_new, how='outer', on=['Balance item class','Total balance and off-balance items'], suffixes=[f'_{old_data_date}',f'_{new_data_date}'])
    data_3_merge = diff_by_cols(data_3,data_3_merge, data_for_cols=False)

    ### data_4
    data_4_merge = data_4_old.merge(data_4_new, how='outer', on=['Balance item class','Off- balance items'], suffixes=[f'_{old_data_date}',f'_{new_data_date}'])
    data_4_merge = data_4_merge.fillna(0)
    data_4_merge = diff_by_cols(data_4,data_4_merge,2,data_for_cols=False)

    ### data_5
    data_5_merge = data_5_old.merge(data_5_new, how='outer', on=['Balance item class','Balance item name','Exposure currency type'], suffixes=[f'_{old_data_date}',f'_{new_data_date}'])
    data_5_merge = data_5_merge.fillna(0)
    data_5_merge = diff_by_cols(data_5,data_5_merge,3,data_for_cols=False)

    ### TO EXCEL
    if print_to_excel == True:
        with pd.ExcelWriter(Output_file, engine='openpyxl', mode='a', if_sheet_exists='overlay') as writer:
            count_row = 0
            pd.DataFrame({'company':company_name},index=[0]).to_excel(writer, header=False, index=False, sheet_name=company_name, startrow=count_row)
            count_row += 2
            files_df_couple.loc[string_id:string_id,:].to_excel(writer, header=True, index=False, sheet_name=company_name, startrow=count_row)
            count_row += 3
            data_total.to_excel(writer, header=True, index=False, sheet_name=company_name, startrow=count_row)
            count_row += len(data_total) + 2
            data_total_data_1.to_excel(writer, header=True, index=False, sheet_name=company_name, startrow=count_row)
            count_row += len(data_total_data_1) + 2
            data_3_merge.to_excel(writer, header=True, index=False, sheet_name=company_name, startrow=count_row)
            count_row += len(data_3_merge) + 2
            data_4_merge.to_excel(writer, header=True, index=False, sheet_name=company_name, startrow=count_row)
            count_row += len(data_4_merge) + 2
            data_5_merge.to_excel(writer, header=True, index=False, sheet_name=company_name, startrow=count_row)




    # except Exception as e:
    #     print(e, 'in string ',string_id)

28 nov\BRFTO FX Exposure Model 28.11.2024 - With Pnl & Tax Credit -New Model.xlsx
29 nov\BRFTO FX Exposure Model 29.11.2024 - With Pnl & Tax Credit -New Model.xlsx

C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  asserts_part['class_name_1'] = 'Assets'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liabilities_part['class_name_1'] = 'Liabilities and equity'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:134: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Current assets' 'Non-current assets' 'Current liabilities'
 'Non-current liabilities' 'Equity']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data_5.loc[condition, 'class_name_2'] = data_5.loc[condition, 'name']
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:135: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_5['class_name_2'] = data_5['class_name_2'].fillna(method='ffill')
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  asserts_part['class_name_1'] = 'Assets'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liabilities_part['class_name_1'] = 'Liabilities and equity'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:134: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Current assets' 'Non-current assets' 'Current liabilities'
 'Non-current liabilities' 'Equity']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data_5.loc[condition, 'class_name_2'] = data_5.loc[condition, 'name']
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:135: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_5['class_name_2'] = data_5['class_name_2'].fillna(method='ffill')
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.4873523382922005 28.37111053708525 0.3471115088698789
 0.009134221988186603]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.4929754992300708 28.048942908496425 0.33233522999171583
 0.0019348310125593007]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.1459865286937144 0.0011212791314482065 0.021045861545138
 0.34745985215038644 0.014078296013261037 0.041183063845004156
 0.04839577703353894 0.01368597155583017 0.03306960409082061 0.0
 0.015664406045800307 0.008360355009379105]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:180: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_4_merge = data_4_merge.fillna(0)
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.39881497 0.         0.        ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:185: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_5_merge = data_5_merge.fillna(0)
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[3.72009657e-01 3.71450726e-01 3.95149125e-02 0.00000000e+00
 0.00000000e+00 3.01079517e-02 3.01079517e-02 1.61494536e-01
 8.80404485e-02 0.00000000e+00 3.34799455e-02 9.23567977e-01
 9.23567977e-01 4.21463801e-03 4.21463801e-03 3.33266652e-02
 2.12599359e-01 2.23508769e-01 3.86657570e-02 9.79158487e-03
 9.79158487e-03 0.00000000e+00 0.00000000e+00 5.12148365e-02
 8.48178730e-01 3.55571171e-02 2.19300289e-03 5.33274965e-02
 5.33274965e-02 1.64134310e-01 1.64134310e-01 1.59752866e-04
 1.59752866e-04 2.78700879e-03 1.11665155e-01 1.07502099e-01
 6.91106405e-02 8.63726158e-03 5.05199429e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 2.48933084e-01
 2.48933084e-01 3.30696041e-02 3.30696041e-02 8.53225049e-03
 8.53225049e-03 6.60326638e-03 6.56771032e-03 3.67580888e-03]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])

28 nov\BRSFT FX Exposure Model 28.11.2024 - With Pnl & Tax Credit.xlsx
29 nov\BRSFT FX Exposure Model 29.11.2024 - With Pnl & Tax Credit.xlsx

C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  asserts_part['class_name_1'] = 'Assets'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liabilities_part['class_name_1'] = 'Liabilities and equity'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:134: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Current assets' 'Non-current assets' 'Current liabilities'
 'Non-current liabilities' 'Equity']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data_5.loc[condition, 'class_name_2'] = data_5.loc[condition, 'name']
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:135: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_5['class_name_2'] = data_5['class_name_2'].fillna(method='ffill')
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  asserts_part['class_name_1'] = 'Assets'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liabilities_part['class_name_1'] = 'Liabilities and equity'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:134: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Current assets' 'Non-current assets' 'Current liabilities'
 'Non-current liabilities' 'Equity']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data_5.loc[condition, 'class_name_2'] = data_5.loc[condition, 'name']
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:135: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_5['class_name_2'] = data_5['class_name_2'].fillna(method='ffill')
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.717715017735699 0.8233870825312165 0.7566417730059536 1.0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.7208113624655824 0.8253243250718834 0.7593111355685049 1.0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.7257508950202861 1.0 0.976549105953024 0.8233870825312165
 0.9749679492351387 0.7463017659919894 1.0 0.9462868219800484
 0.9751187834477278 1.0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:180: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_4_merge = data_4_merge.fillna(0)
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.82338708]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:185: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_5_merge = data_5_merge.fillna(0)
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.04567692 0.04567692 1.         0.98136363 0.98152624 1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         0.94628682
 0.94628682 0.97586433 0.97586433 1.         1.         0.11860443
 0.11860443]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])

28 nov\Cópia de BRFHRG FX Exposure 28.11.2024 - With pnl  Tax Credit - New model.xlsx
29 nov\BRFHRG FX Exposure 29.11.2024 - With pnl  Tax Credit - New model.xlsx

C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  asserts_part['class_name_1'] = 'Assets'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liabilities_part['class_name_1'] = 'Liabilities and equity'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:134: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Current assets' 'Non-current assets' 'Current liabilities'
 'Non-current liabilities' 'Equity']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data_5.loc[condition, 'class_name_2'] = data_5.loc[condition, 'name']
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:135: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_5['class_name_2'] = data_5['class_name_2'].fillna(method='ffill')
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  asserts_part['class_name_1'] = 'Assets'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liabilities_part['class_name_1'] = 'Liabilities and equity'
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:134: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Current assets' 'Non-current assets' 'Current liabilities'
 'Non-current liabilities' 'Equity']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data_5.loc[condition, 'class_name_2'] = data_5.loc[condition, 'name']
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:135: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_5['class_name_2'] = data_5['class_name_2'].fillna(method='ffill')
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[3.7177144473662844 0.030059611060911498 0.4442280875630086
 0.12479743833892862]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[3.683515547024225 0.042265048880625294 0.4512217539744184
 0.13581072386433346]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.1478737559056476 0.0006305899668404374 0.14404135186331293
 0.010628621101149564 0.0 0.05664081410975012 0.10227734806533281
 3.2015463589800637e-06 0.0 0.12469660000048689]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:180: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_4_merge = data_4_merge.fillna(0)
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.02237741 0.         0.        ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\3207565341.py:185: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_5_merge = data_5_merge.fillna(0)
C:\Users\KlimovaAnnaA\AppData\Local\Temp\ipykernel_10068\4026790028.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1.85504175e-01 1.54754373e-01 1.88349549e-01 1.61982184e-04
 0.00000000e+00 6.31106422e-03 1.41116284e-01 0.00000000e+00
 3.15698519e-02 7.42126719e-03 0.00000000e+00 5.26541693e-01
 2.16557026e-02 9.42625221e-02 0.00000000e+00 0.00000000e+00
 4.10599630e-02 2.41778219e-01 1.55205510e-01 5.29632398e-01
 4.61397775e-02 3.20154636e-06 0.00000000e+00 2.97681149e-03
 8.20230901e-03 2.19247552e-03 9.36916937e-03 1.74183140e-02
 1.75097934e-02 1.75930797e-02 1.19748199e-02 8.22754165e-03
 8.76893550e-03]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_merge.loc[condition, f'{col}_pct_diff'] = abs(data_merge.loc[condition,f'{col}_diff'] / data_merge.loc[condition,col_cols_list[0]])

In [597]:
data_3_merge

,Balance item class,Total balance and off-balance items,Value_28.11.2024,Value_29.11.2024
0,Assets,"BRL denominated, in OCP",546167.399535,625900.482278
1,Assets,"BRL, out of OCP",5921265.02116,5914625.63026
2,Assets,Non Monetary denominated,3576267.11259,3651532.73509
3,Assets,Off balance,421291.19026,274909.41558
4,Assets,TOTAL,9786876.11059,9924658.64952
5,Assets,USD denominated,-256823.422695,-267400.198108
6,Liabilities and equity,"BRL denominated, in OCP",-367733.92124,-385530.6901
7,Liabilities and equity,"BRL, out of OCP",-976644.01577,-990010.33799
8,Liabilities and equity,Non Monetary denominated,1386754.2074,1340894.79479
9,Liabilities and equity,Off balance,-426450.72656,-426450.72656
10,Liabilities and equity,TOTAL,-10593680.68057,-10759624.39627
11,Liabilities and equity,USD denominated,-10636056.95096,-10724978.16297

check

In [ ]:
col_1_name_net = 'Total net exposure'
col_1_name_data_1 = 'Total exposure split by Balance/Off balance'

str_to_find = 'Net Exposure Balance BRL'
str_to_find = str_to_find.strip().lower()
data_total = data_1_merge[data_1_merge.name.str.lower().str.contains(str_to_find)]
data_total.columns = [col_1_name_net] + data_total.columns.tolist()[1:]

data_total_data_1 = data_1_merge[~data_1_merge.name.str.lower().str.contains(str_to_find)]
data_total_data_1.columns = [col_1_name_data_1] + data_total_data_1.columns.tolist()[1:]

In [ ]:
col_1_name_data_3 = 'Total balance and off-balance items'

data_3_tr = data_3.transpose()
# rename cols and drop col name string
data_3_tr.columns = data_3_tr.iloc[0,:]
data_3_tr = data_3_tr.iloc[1:,:]
data_3_tr['name'] = data_3_tr.index
data_3_tr = data_3_tr.reset_index(drop=True)
# to parts
assets_col = [x for x in data_3_tr.columns.tolist() if 'assets' in x][0]
liabilities_col = [x for x in data_3_tr.columns.tolist() if 'liabilities' in x][0]


assets_data = data_3_tr[['name',assets_col]]
assets_data.columns = [col_1_name_data_3, 'Value']
assets_data['Balance item class'] = 'Assets'
liabilities_data = data_3_tr[['name',liabilities_col]]
liabilities_data.columns = [col_1_name_data_3, 'Value']
liabilities_data['Balance item class'] = 'Liabilities and equity'

data_3_tr = pd.concat([assets_data,liabilities_data], axis=0)
data_3_tr = data_3_tr.iloc[:,[2,0,1]]

data_3 = data_3_tr

In [ ]:
# del string
str_to_find = 'Industrialization'
str_to_find = str_to_find.strip().lower()
data_4 = data_4[~data_4.name.str.lower().str.contains(str_to_find)]

# total to previous part
str_to_find = 'total'

data_to_3 = data_4[data_4.name.str.lower().str.contains(str_to_find)]
data_to_3 = data_to_3.iloc[:,:3]
data_to_3.columns = ['Balance item class', col_1_name_data_3, 'Value']
data_to_3.iloc[:,1] = 'Off balance'

data_3 = pd.concat([data_3,data_to_3],axis=0)

#final 4 part
data_4 = data_4[~data_4.name.str.lower().str.contains(str_to_find)]
data_4 = data_4.iloc[:, :3]
data_4.columns = ['Balance item class','Off- balance items','Value']

In [ ]:
data_5_melt = data_5.melt(id_vars=data_5.columns.tolist()[:3], value_vars=data_5.columns.tolist()[3:], value_name='Value', var_name='Exposure currency type')
data_5_melt = data_5_melt.iloc[:,1:]
data_5_melt.columns = ['Balance item class','Balance item name'] + data_5_melt.columns.tolist()[2:]
data_5 = data_5_melt

In [ ]:
# to excel
data_total
data_total_data_1

# before merge
data_3
data_4
data_5

,Balance item class,Off- balance items,Value
0,Assets,Sales Contracts,278274.40705
1,Assets,Derivatives position (short USD / Long BRL),0
2,Assets,Tax Credit,314643
4,Liabilities and equity,CAPEX + OPEX 12M Forecast,-387388.236194
6,Liabilities and equity,Derivatives position (long USD / short BRL),NaN